// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: relay.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RelayKind int32

const (
	RelayKind_RELAY_KIND_UNSPECIFIED RelayKind = 0
	RelayKind_RELAY_KIND_OPEN        RelayKind = 1
	RelayKind_RELAY_KIND_OPEN_ACK    RelayKind = 2
	RelayKind_RELAY_KIND_DATA        RelayKind = 3
	RelayKind_RELAY_KIND_ACK         RelayKind = 4
	RelayKind_RELAY_KIND_CLOSE       RelayKind = 5
	RelayKind_RELAY_KIND_PING        RelayKind = 6
	RelayKind_RELAY_KIND_ERROR       RelayKind = 7
)

// Enum value maps for RelayKind.
var (
	RelayKind_name = map[int32]string{
		0: "RELAY_KIND_UNSPECIFIED",
		1: "RELAY_KIND_OPEN",
		2: "RELAY_KIND_OPEN_ACK",
		3: "RELAY_KIND_DATA",
		4: "RELAY_KIND_ACK",
		5: "RELAY_KIND_CLOSE",
		6: "RELAY_KIND_PING",
		7: "RELAY_KIND_ERROR",
	}
	RelayKind_value = map[string]int32{
		"RELAY_KIND_UNSPECIFIED": 0,
		"RELAY_KIND_OPEN":        1,
		"RELAY_KIND_OPEN_ACK":    2,
		"RELAY_KIND_DATA":        3,
		"RELAY_KIND_ACK":         4,
		"RELAY_KIND_CLOSE":       5,
		"RELAY_KIND_PING":        6,
		"RELAY_KIND_ERROR":       7,
	}
)

func (x RelayKind) Enum() *RelayKind {
	p := new(RelayKind)
	*p = x
	return p
}

func (x RelayKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelayKind) Descriptor() protoreflect.EnumDescriptor {
	return file_relay_proto_enumTypes[0].Descriptor()
}

func (RelayKind) Type() protoreflect.EnumType {
	return &file_relay_proto_enumTypes[0]
}

func (x RelayKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelayKind.Descriptor instead.
func (RelayKind) EnumDescriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{0}
}

type RelayEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RelayId       string                 `protobuf:"bytes,1,opt,name=relay_id,json=relayId,proto3" json:"relay_id,omitempty"`
	Kind          RelayKind              `protobuf:"varint,2,opt,name=kind,proto3,enum=notifier.relay.v1.RelayKind" json:"kind,omitempty"`
	SenderSession *SessionRef            `protobuf:"bytes,3,opt,name=sender_session,json=senderSession,proto3" json:"sender_session,omitempty"`
	TargetSession *SessionRef            `protobuf:"bytes,4,opt,name=target_session,json=targetSession,proto3" json:"target_session,omitempty"`
	Seq           uint64                 `protobuf:"varint,5,opt,name=seq,proto3" json:"seq,omitempty"`
	AckSeq        uint64                 `protobuf:"varint,6,opt,name=ack_seq,json=ackSeq,proto3" json:"ack_seq,omitempty"`
	Payload       []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	SentAtMs      int64                  `protobuf:"varint,8,opt,name=sent_at_ms,json=sentAtMs,proto3" json:"sent_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayEnvelope) Reset() {
	*x = RelayEnvelope{}
	mi := &file_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayEnvelope) ProtoMessage() {}

func (x *RelayEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayEnvelope.ProtoReflect.Descriptor instead.
func (*RelayEnvelope) Descriptor() ([]byte, []int) {
	return file_relay_proto_rawDescGZIP(), []int{0}
}

func (x *RelayEnvelope) GetRelayId() string {
	if x != nil {
		return x.RelayId
	}
	return ""
}

func (x *RelayEnvelope) GetKind() RelayKind {
	if x != nil {
		return x.Kind
	}
	return RelayKind_RELAY_KIND_UNSPECIFIED
}

func (x *RelayEnvelope) GetSenderSession() *SessionRef {
	if x != nil {
		return x.SenderSession
	}
	return nil
}

func (x *RelayEnvelope) GetTargetSession() *SessionRef {
	if x != nil {
		return x.TargetSession
	}
	return nil
}

func (x *RelayEnvelope) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *RelayEnvelope) GetAckSeq() uint64 {
	if x != nil {
		return x.AckSeq
	}
	return 0
}

func (x *RelayEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RelayEnvelope) GetSentAtMs() int64 {
	if x != nil {
		return x.SentAtMs
	}
	return 0
}

var File_relay_proto protoreflect.FileDescriptor

const file_relay_proto_rawDesc = "" +
	"\n" +
	"\vrelay.proto\x12\x11notifier.relay.v1\x1a\fclient.proto\"\xcd\x02\n" +
	"\rRelayEnvelope\x12\x19\n" +
	"\brelay_id\x18\x01 \x01(\tR\arelayId\x120\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1c.notifier.relay.v1.RelayKindR\x04kind\x12E\n" +
	"\x0esender_session\x18\x03 \x01(\v2\x1e.notifier.client.v1.SessionRefR\rsenderSession\x12E\n" +
	"\x0etarget_session\x18\x04 \x01(\v2\x1e.notifier.client.v1.SessionRefR\rtargetSession\x12\x10\n" +
	"\x03seq\x18\x05 \x01(\x04R\x03seq\x12\x17\n" +
	"\aack_seq\x18\x06 \x01(\x04R\x06ackSeq\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x12\x1c\n" +
	"\n" +
	"sent_at_ms\x18\b \x01(\x03R\bsentAtMs*\xbf\x01\n" +
	"\tRelayKind\x12\x1a\n" +
	"\x16RELAY_KIND_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fRELAY_KIND_OPEN\x10\x01\x12\x17\n" +
	"\x13RELAY_KIND_OPEN_ACK\x10\x02\x12\x13\n" +
	"\x0fRELAY_KIND_DATA\x10\x03\x12\x12\n" +
	"\x0eRELAY_KIND_ACK\x10\x04\x12\x14\n" +
	"\x10RELAY_KIND_CLOSE\x10\x05\x12\x13\n" +
	"\x0fRELAY_KIND_PING\x10\x06\x12\x14\n" +
	"\x10RELAY_KIND_ERROR\x10\aB2Z0github.com/tursom/turntf-go/internal/proto;protob\x06proto3"

var (
	file_relay_proto_rawDescOnce sync.Once
	file_relay_proto_rawDescData []byte
)

func file_relay_proto_rawDescGZIP() []byte {
	file_relay_proto_rawDescOnce.Do(func() {
		file_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relay_proto_rawDesc), len(file_relay_proto_rawDesc)))
	})
	return file_relay_proto_rawDescData
}

var file_relay_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_relay_proto_goTypes = []any{
	(RelayKind)(0),        // 0: notifier.relay.v1.RelayKind
	(*RelayEnvelope)(nil), // 1: notifier.relay.v1.RelayEnvelope
	(*SessionRef)(nil),    // 2: notifier.client.v1.SessionRef
}
var file_relay_proto_depIdxs = []int32{
	0, // 0: notifier.relay.v1.RelayEnvelope.kind:type_name -> notifier.relay.v1.RelayKind
	2, // 1: notifier.relay.v1.RelayEnvelope.sender_session:type_name -> notifier.client.v1.SessionRef
	2, // 2: notifier.relay.v1.RelayEnvelope.target_session:type_name -> notifier.client.v1.SessionRef
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_relay_proto_init() }
func file_relay_proto_init() {
	if File_relay_proto != nil {
		return
	}
	file_client_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relay_proto_rawDesc), len(file_relay_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relay_proto_goTypes,
		DependencyIndexes: file_relay_proto_depIdxs,
		EnumInfos:         file_relay_proto_enumTypes,
		MessageInfos:      file_relay_proto_msgTypes,
	}.Build()
	File_relay_proto = out.File
	file_relay_proto_goTypes = nil
	file_relay_proto_depIdxs = nil
}
